### ISSUE TITLE
Mise en place du canvas et d’un premier élément

### ISSUE THREAD

**Issue by julienalofs** [julienalofs/CoderBrick#1]
- [x] Création du fichier de HTML de base (voir tutorial HTML)
- Code java inside html
- Exemple : https://www.w3schools.com/graphics/game_canvas.asp
- [x] Création du tutoriel dans le wiki
- Expliquer la notion d’objet JAVA (état + méthode)

Exercices : 
- Un élément rectangle 
- Un élément disque 
- Changer la couleur de l’élément 
- Changer la position 
- Changer la taille 
- Changer l'orientation

**Comment by julienalofs** [comment]
@Tuxbee  je t'assigne le bug pour que tu valides mon travail.

**Comment by Tuxbee** [comment]
J'ai tout relu, cela me semble super.
J'ai ajouté quelques détails à propos de l'opérateur new et du constructeur dans ta section "objet".
Si c'est OK pour toi, close l'issue.

**Comment by julienalofs** [comment]
Reviewed by @Tuxbee .
