### ISSUE TITLE
Conversion du premier élément en plateforme commandée via le clavier

### ISSUE THREAD

**Issue by julienalofs** [julienalofs/CoderBrick#2]
- [x] Code java dans un fichier séparé
- [x] Création du tutoriel dans le wiki

Exercice : 
- Changer la touche 
- Changer la vitesse de mouvement 
- Gérer les bornes de la plateforme

**Comment by Tuxbee** [comment]
Le tuto est écrit.
J'ai besoin d'une review ;-).

**Comment by julienalofs** [comment]
@Tuxbee 
Pour moi, le code rentré est trop compliqué. Je retirerais le "requestAnimationFrame" et l'accélération, qui n'apporte rien pour cette étape.

Mais c'est toi qui vois, c'est ton tuto ;)

**Comment by Tuxbee** [comment]
Je le laisse pour cette fois 😉.
