### ISSUE TITLE
Création d’un décor délimitant la zone de jeu

### ISSUE THREAD

**Issue by julienalofs** [julienalofs/CoderBrick#3]
- [x] Code source

- [x] Wiki

Exercices : 
- Modifier les bornes de mouvement de la plateforme 
- Ajouter des éléments non rectangulaires comme décor (par exemple dans les coins) 
- Ajouter des briques incassables (éléments de décor)

**Comment by julienalofs** [comment]
@Tuxbee, peux-tu faire la review ?

**Comment by Tuxbee** [comment]
Pour moi OK. (petite correction dans le Wiki)
