### ISSUE TITLE
Création de la balle rebondissante

### ISSUE THREAD

**Issue by julienalofs** [julienalofs/CoderBrick#4]
- [x] Code source
- [x] Wiki

Exercices:
- Ajouter le rebond sur les briques

**Comment by julienalofs** [comment]
Développement réalisé dans la branche "Balle_rebondissante".

En attente de review

**Comment by Tuxbee** [comment]
Problème de gestion du rayon dans certain cas.
Enlever la direction dans le test.

**Comment by julienalofs** [comment]
Le problème de collision vient du fait que la balle se retrouve parfois à l'intérieur du bloc étant donné qu'on ne test pas les collision avant le mouvement.

Il faudrait complexifier le modèle et faire quelque chose du genre:
- je veux déplacer la balle de x vers la droite
- mais un obstacle se trouve à x-y
- donc je ne déplace la balle que de x-y et je rebondis

Pour l'instant ,on déplace la balle de x, puis on regarde si il y a collision et donc on se retrouver avec la balle à l'intérieur de l'obstacle

**Comment by julienalofs** [comment]
Perso, je préférerais dédié un tuto à la résolution de ce problème que de le corriger ici

**Comment by julienalofs** [comment]
> Dans le tuto 2, on ajoute une fonction updatePosi à la plateforme pour gérer la position.
> Dans le tuto 4, on ajoute une fonction update qui affiche la balle et gère la position.
> Pourquoi ne pas avoir que update dans les 2 cas (comme dans notre code) ?
> Ou alors, avoir dans les 2 cas updatePosi dans le Tuto...
> 

J'ai retiré la fonction updatePosi dans le tuto 2

**Comment by Tuxbee** [comment]
> 
> 
> Perso, je préférerais dédié un tuto à la résolution de ce problème que de le corriger ici

Je comprends oui.

> 
> 
> > Dans le tuto 2, on ajoute une fonction updatePosi à la plateforme pour gérer la position.
> > Dans le tuto 4, on ajoute une fonction update qui affiche la balle et gère la position.
> > Pourquoi ne pas avoir que update dans les 2 cas (comme dans notre code) ?
> > Ou alors, avoir dans les 2 cas updatePosi dans le Tuto...
> 
> J'ai retiré la fonction updatePosi dans le tuto 2

Merci, ça sera plus claire je pense.
